[params]
favicon = "/favicon.ico"
[taxonomies]
  category = "categories"
  tag = "tags"
 [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      reading_speed = 180
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

